# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(451, 516)
        MainWindow.setStyleSheet("background:#1E2024\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 70, 231, 31))
        self.comboBox.setStyleSheet("font: Luminari, fantasy;\n"
" border-radius: 8px; /* Уголки */\n"
"color: #F3AE0F; /* Цвет текста */\n"
"background: rgba(138,146,164,0.8)\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(10, 110, 231, 31))
        self.comboBox_2.setStyleSheet("\n"
" border-radius: 8px; /* Уголки */\n"
"font: Luminari, fantasy;\n"
"color: #F3AE0F; /* Цвет текста */\n"
"background: rgba(138,146,164,0.8)\n"
"")
        self.comboBox_2.setObjectName("comboBox_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(100, 410, 241, 71))
        self.pushButton.setStyleSheet("\n"
"  display: inline-block;\n"
"  color: white;\n"
"  text-decoration: none;\n"
"  padding: .5em 2em;\n"
"  outline: none;\n"
"  border-width: 2px 0;\n"
"  border-style: solid none;\n"
"  border-color: #FDBE33 #000 #D77206;\n"
"  border-radius: 6px;\n"
"  background: linear-gradient(#F3AE0F, #E38916) #E38916;\n"
"  transition: 0.2s;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 291, 41))
        font = QtGui.QFont()
        font.setFamily(",fantasy")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("font: Luminari, fantasy;\n"
"font-size: 11pt; /* Размер шрифта в пунктах */\n"
"color: #F3AE0F; /* Цвет текста */\n"
" border-radius: 8px; /* Уголки */\n"
"background: rgba(138,146,164,0.8)\n"
"\n"
"")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 170, 251, 31))
        self.lineEdit_2.setStyleSheet(" border-radius: 8px; /* Уголки */\n"
"font: Luminari, fantasy;\n"
"font-size: 11pt; /* Размер шрифта в пунктах */\n"
"color: #F3AE0F; /* Цвет текста */\n"
"background: rgba(138,146,164,0.8)")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 220, 251, 31))
        self.lineEdit_3.setStyleSheet(" border-radius: 8px; /* Уголки */\n"
"font: Luminari, fantasy;\n"
"font-size: 11pt; /* Размер шрифта в пунктах */\n"
"color: #F3AE0F; /* Цвет текста */\n"
"background: rgba(138,146,164,0.8)")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 70, 111, 31))
        self.pushButton_2.setStyleSheet("\n"
"  display: inline-block;\n"
"  color: white;\n"
"  text-decoration: none;\n"
"  padding: .5em 2em;\n"
"  outline: none;\n"
"  border-width: 2px 0;\n"
"  border-style: solid none;\n"
"  border-color: #FDBE33 #000 #D77206;\n"
"  border-radius: 6px;\n"
"  background: linear-gradient(#F3AE0F, #E38916) #E38916;\n"
"  transition: 0.2s;\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(270, 110, 111, 31))
        self.pushButton_3.setStyleSheet("\n"
"  display: inline-block;\n"
"  color: white;\n"
"  text-decoration: none;\n"
"  padding: .5em 2em;\n"
"  outline: none;\n"
"  border-width: 2px 0;\n"
"  border-style: solid none;\n"
"  border-color: #FDBE33 #000 #D77206;\n"
"  border-radius: 6px;\n"
"  background: linear-gradient(#F3AE0F, #E38916) #E38916;\n"
"  transition: 0.2s;\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(310, 10, 131, 41))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_4.setStyleSheet("\n"
"  display: inline-block;\n"
"  color: white;\n"
"  text-decoration: none;\n"
"  padding: .5em 2em;\n"
"  outline: none;\n"
"  border-width: 2px 0;\n"
"  border-style: solid none;\n"
"  border-color: #FDBE33 #000 #D77206;\n"
"  border-radius: 6px;\n"
"  background: linear-gradient(#F3AE0F, #E38916) #E38916;\n"
"  transition: 0.2s;\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 300, 431, 91))
        self.plainTextEdit.setStyleSheet("font-size: 11pt; /* Размер шрифта в пунктах */\n"
"    background: rgba(138,146,164,0.8); /* Цвет фона */\n"
"   color: #F3AE0F; /* Цвет текста */\n"
"    padding: 10px; /* Поля вокруг текста */ \n"
"border-radius: 8px; /* Уголки */\n"
"\n"
"font: Luminari, fantasy;\n"
"")
        self.plainTextEdit.setObjectName("plainTextEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "выполнить"))
        self.pushButton_2.setText(_translate("MainWindow", "применить"))
        self.pushButton_3.setText(_translate("MainWindow", "применить"))
        self.pushButton_4.setText(_translate("MainWindow", "проверить имя"))
